In [1]:
import requests
import pandas as pd

In [2]:
final=pd.DataFrame()

for j in range(1,501):
    
    response=requests.get('https://api.themoviedb.org/3/movie/popular?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(j)).json()
    
    popularity=[]
    vote_count=[]
    original_language=[]
    title=[]
    vote_average=[]
    overview=[]
    release_date=[]


    for i in response['results']:

        popularity.append(i['popularity'])
        vote_count.append(i['vote_count'])
        original_language.append(i['original_language'])
        title.append(i['title'])
        vote_average.append(i['vote_average'])
        overview.append(i['overview'])
        try:
            release_date.append(i['release_date'])
        except:
            release_date.append('NAN')
            

    d={'title':title, 'overview':overview, 'original_language':original_language, 'release_date':release_date, 'popularity':popularity, 'vote_count':vote_count, 'vote_average':vote_average}

    df=pd.DataFrame(d)
    
    final=final.append(df, ignore_index=True)

In [3]:
final

,title,overview,original_language,release_date,popularity,vote_count,vote_average
0,Ad Astra,"The near future, a time when both hope and har...",en,2019-09-17,462.659,2853,5.9
1,Ant-Man,Armed with the astonishing ability to shrink i...,en,2015-07-14,223.823,13611,7.1
2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,en,2020-01-15,235.696,2530,7.1
3,Bloodshot,"After he and his wife are murdered, marine Ray...",en,2020-03-05,247.853,1349,7.2
4,The Twilight Saga: Eclipse,Bella once again finds herself surrounded by d...,en,2010-06-23,143.316,5687,6.1
...,...,...,...,...,...,...,...
9995,Stir Crazy,"New Yorkers, Skip Donahue and Harry Monroe hav...",en,1980-12-12,7.923,225,6.6
9996,Keeping Mum,A pastor preoccupied with writing the perfect ...,en,2005-12-02,10.952,308,6.6
9997,The Double,The mysterious murder of a US senator bearing ...,en,2011-10-27,10.951,391,5.8
9998,Dave Chappelle: Deep in the Heart of Texas,Comedy icon Dave Chappelle makes his triumphan...,en,2017-03-21,7.638,117,8.0
9999,Michael Moore in TrumpLand,Oscar-winner Michael Moore dives right into ho...,en,2016-10-18,6.986,60,6.2

In [4]:
final.to_csv('movies.csv')